### ISSUE TITLE
댓글 기능이 없어서 이슈로 등록합니다 :)

### ISSUE THREAD

**Issue by JaeYeopHan** [heecheolman/heecheolman-blog-code#18]
> https://heecheolman.github.io/#/what/posts/5 에서,

제 발표와 관련된 글이다 보니 이렇게까지 찾아와서 이슈로 등록합니다!ㅎㅎ

```
### Audits 도구 이용

- SEO
  - `서버사이드렌더링(SSR) 이 제대로 이루어지는가?`
```

이 부분은 아쉽게도 보완이 필요할 것 같습니다!ㅎㅎ

SSR을 통하여 CSR의 한계점 중 하나인 SEO를 극복할 수 있는 것은 맞지만 SEO 점수가 SSR이 제대로 이루어지는가를 의미하지는 않습니다! 말 그대로 SEO(Search Engine Optimization)이 잘 되었는가를 측정하며 대표적인 예로는 크롤러가 수집하기 위한 정보가 있는지 meta 태그가 잘 설정되어 있는지 등을 의미합니다~

깔끔한 후기 다시 한번 감사합니다. 🙏

**Comment by heecheolman** [comment]
피드백 남겨주신걸 지금에서야 봤네요 ㅎㅎ
SEO(검색엔진최적화) 에 대해서 그 당시 잘못 알고있었네요 말씀해주신 검색엔진 최적화 관련이 맞습니다 ㅎㅎ
피드백 감사합니다 !
